# Type stub for the compiled extension module.
#
# `_hier_config_rust` is a `.so` built by maturin, so type checkers cannot
# introspect it. Without this stub every `from _hier_config_rust import ...`
# in the re-export shims resolves to `Unknown`, which under pyright's strict
# mode cascades into dozens of errors across `hier_config/` and makes the
# package's own source unverifiable.
#
# The authoritative, documented signatures live in the `hier_config/*.pyi`
# stubs beside the shims -- those are what mkdocstrings renders and what
# downstream users see. This file deliberately re-exports from them rather
# than restating them, so there is exactly one copy of each signature and the
# two can never drift.
#
# This stub is repo-local (see `mypy_path` / `stubPath` in pyproject.toml) and
# is not shipped: `_hier_config_rust` is underscore-prefixed precisely because
# callers are meant to reach these types through `hier_config`, which is fully
# typed via `py.typed`.

from collections.abc import Iterable
from ipaddress import IPv4Address, IPv4Interface

from hier_config.base import HConfigBase as HConfigBase
from hier_config.child import HConfigChild as HConfigChild
from hier_config.children import HConfigChildren as HConfigChildren
from hier_config.exceptions import DuplicateChildError as DuplicateChildError
from hier_config.exceptions import HierConfigError as HierConfigError
from hier_config.platforms.models import (
    InterfaceDot1qMode,
    InterfaceDuplex,
    NACHostMode,
    StackMember,
    Vlan,
)
from hier_config.root import HConfig as HConfig
from hier_config.workflows import WorkflowRemediation as WorkflowRemediation

# Declared here rather than re-exported: this iterator is returned by
# `HConfigChildren.__iter__` but has no stub of its own under `hier_config/`.
class HConfigChildrenIter:
    def __iter__(self) -> HConfigChildrenIter: ...
    def __next__(self) -> HConfigChild: ...

# The native config-view classes. These have no `hier_config/*.pyi` counterpart
# because `hier_config.platforms.view_base` wraps rather than re-exports them:
# the public `HConfigViewBase` / `ConfigViewInterfaceBase` facades are ordinary
# Python classes that delegate to these, so their signatures are declared here.
class NativeConfigViewInterface:
    def __init__(self, config: HConfigChild) -> None: ...
    @property
    def config(self) -> HConfigChild: ...
    @property
    def bundle_id(self) -> str | None: ...
    @property
    def bundle_member_interfaces(self) -> Iterable[str]: ...
    @property
    def bundle_name(self) -> str | None: ...
    @property
    def description(self) -> str: ...
    @property
    def dot1q_mode(self) -> InterfaceDot1qMode | None: ...
    @property
    def duplex(self) -> InterfaceDuplex: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def has_nac(self) -> bool: ...
    @property
    def ipv4_interface(self) -> IPv4Interface | None: ...
    @property
    def ipv4_interfaces(self) -> Iterable[IPv4Interface]: ...
    @property
    def is_bundle(self) -> bool: ...
    @property
    def is_loopback(self) -> bool: ...
    @property
    def is_subinterface(self) -> bool: ...
    @property
    def is_svi(self) -> bool: ...
    @property
    def module_number(self) -> int | None: ...
    @property
    def nac_control_direction_in(self) -> bool: ...
    @property
    def nac_host_mode(self) -> NACHostMode | None: ...
    @property
    def nac_mab_first(self) -> bool: ...
    @property
    def nac_max_dot1x_clients(self) -> int: ...
    @property
    def nac_max_mab_clients(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def native_vlan(self) -> int | None: ...
    @property
    def number(self) -> str: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def poe(self) -> bool: ...
    @property
    def port_number(self) -> int: ...
    @property
    def speed(self) -> tuple[int, ...] | None: ...
    @property
    def subinterface_number(self) -> int | None: ...
    @property
    def tagged_all(self) -> bool: ...
    @property
    def tagged_vlans(self) -> tuple[int, ...]: ...
    @property
    def vrf(self) -> str: ...

class NativeHConfigView:
    def __init__(self, config: HConfig) -> None: ...
    @property
    def config(self) -> HConfig: ...
    def dot1q_mode_from_vlans(
        self,
        untagged_vlan: int | None = None,
        tagged_vlans: tuple[int, ...] | None = None,
        tagged_all: bool = False,
    ) -> InterfaceDot1qMode | None: ...
    @property
    def hostname(self) -> str | None: ...
    @property
    def location(self) -> str: ...
    @property
    def ipv4_default_gw(self) -> IPv4Address | None: ...
    @property
    def interfaces(self) -> Iterable[HConfigChild]: ...
    @property
    def interface_views(self) -> Iterable[NativeConfigViewInterface]: ...
    def interface_view_by_name(
        self, name: str
    ) -> NativeConfigViewInterface | None: ...
    @property
    def interfaces_names(self) -> Iterable[str]: ...
    @property
    def bundle_interface_views(self) -> Iterable[NativeConfigViewInterface]: ...
    @property
    def module_numbers(self) -> Iterable[int]: ...
    @property
    def interface_names_mentioned(self) -> frozenset[str]: ...
    @property
    def stack_members(self) -> Iterable[StackMember]: ...
    @property
    def vlans(self) -> Iterable[Vlan]: ...
    @property
    def vlan_ids(self) -> frozenset[int]: ...

def get_platform_rules_json(platform_str: str) -> str: ...
def driver_swap_negation(platform_str: str, text: str) -> str: ...
def convert_to_set_commands(config_raw: str) -> str: ...
def config_preprocessor(platform_str: str, config_text: str) -> str: ...

__all__ = (
    "DuplicateChildError",
    "HConfig",
    "HConfigBase",
    "HConfigChild",
    "HConfigChildren",
    "HConfigChildrenIter",
    "HierConfigError",
    "NativeConfigViewInterface",
    "NativeHConfigView",
    "WorkflowRemediation",
    "config_preprocessor",
    "convert_to_set_commands",
    "driver_swap_negation",
    "get_platform_rules_json",
)
