# This file is automatically generated by pyo3_stub_gen

import builtins
import collections.abc
import ipaddress
import os
import typing

import typing_extensions

import hier_config._typing
import hier_config.formats
import hier_config.models
import hier_config.platforms.driver_base
import hier_config.platforms.models
import hier_config.tree_algorithms

__all__ = [
    "ConfigViewInterface",
    "DuplicateChildError",
    "HConfig",
    "HConfigBase",
    "HConfigChild",
    "HConfigChildren",
    "HConfigChildrenIter",
    "HConfigView",
    "HierConfigError",
    "InvalidConfigError",
    "WorkflowRemediation",
    "__version__",
    "config_preprocessor",
    "convert_to_set_commands",
    "driver_swap_negation",
    "formats_from_json",
    "formats_from_xml",
    "formats_to_gnmi_json",
    "formats_to_json",
    "formats_to_netconf_xml",
    "formats_to_xml",
    "get_platform_rules_json",
]

__version__: builtins.str

class ConfigViewInterface:
    r"""
    A structured, read-only view over a single interface.
    """
    @property
    def config(self) -> HConfigChild:
        r"""
        The `HConfigChild` holding this interface's config block.
        """
    @property
    def description(self) -> str:
        r"""
        The interface description, or an empty string when unset.
        """
    @property
    def enabled(self) -> bool:
        r"""
        Whether the interface is administratively enabled.
        """
    @property
    def ipv4_interface(self) -> ipaddress.IPv4Interface | None:
        r"""
        The first configured IPv4 interface address, if any.
        """
    @property
    def ipv4_interfaces(self) -> list[ipaddress.IPv4Interface]:
        r"""
        Every configured IPv4 interface address.
        """
    @property
    def is_loopback(self) -> bool:
        r"""
        Whether this is a loopback interface.
        """
    @property
    def is_subinterface(self) -> bool:
        r"""
        Whether this is a subinterface of another interface.
        """
    @property
    def is_svi(self) -> bool:
        r"""
        Whether this is a switched virtual interface.
        """
    @property
    def name(self) -> str:
        r"""
        The interface name, e.g. `GigabitEthernet1/0/1`.
        """
    @property
    def number(self) -> str:
        r"""
        The numeric portion of the interface name.
        """
    @property
    def parent_name(self) -> str | None:
        r"""
        The parent interface's name when this is a subinterface.
        """
    @property
    def port_number(self) -> int | None:
        r"""
        The port portion of the interface number.
        """
    @property
    def subinterface_number(self) -> int | None:
        r"""
        The subinterface portion of the interface number.
        """
    @property
    def vrf(self) -> str:
        r"""
        The VRF this interface belongs to, or an empty string.
        """
    @property
    def bundle_id(self) -> str | None:
        r"""
        The bundle this interface is a member of, if any.
        """
    @property
    def bundle_name(self) -> str | None:
        r"""
        The name of the bundle this interface is a member of, if any.
        """
    @property
    def is_bundle(self) -> bool:
        r"""
        Whether this interface is itself a bundle.
        """
    @property
    def bundle_member_interfaces(self) -> list[str]:
        r"""
        The names of the interfaces bundled into this one.
        """
    @property
    def dot1q_mode(self) -> hier_config.platforms.models.InterfaceDot1qMode | None:
        r"""
        The 802.1Q mode of this switchport, if it is one.
        """
    @property
    def native_vlan(self) -> int | None:
        r"""
        The untagged VLAN of this switchport, if it has one.
        """
    @property
    def tagged_all(self) -> bool:
        r"""
        Whether every VLAN is tagged on this switchport.
        """
    @property
    def tagged_vlans(self) -> tuple[int, ...]:
        r"""
        The VLANs tagged on this switchport.
        """
    @property
    def has_nac(self) -> bool:
        r"""
        Whether network access control is configured on this interface.
        """
    @property
    def nac_control_direction_in(self) -> bool:
        r"""
        Whether NAC control is applied to inbound traffic only.
        """
    @property
    def nac_host_mode(self) -> hier_config.platforms.models.NACHostMode | None:
        r"""
        The configured NAC host mode, if any.
        """
    @property
    def nac_mab_first(self) -> bool:
        r"""
        Whether MAC authentication bypass is attempted before 802.1X.
        """
    @property
    def nac_max_dot1x_clients(self) -> int | None:
        r"""
        The maximum number of 802.1X clients, when the platform reports one.
        """
    @property
    def nac_max_mab_clients(self) -> int | None:
        r"""
        The maximum number of MAB clients, when the platform reports one.
        """
    @property
    def is_physical(self) -> bool:
        r"""
        Whether this interface is backed by physical hardware.
        """
    @property
    def duplex(self) -> hier_config.platforms.models.InterfaceDuplex | None:
        r"""
        The configured duplex setting, if any.
        """
    @property
    def module_number(self) -> int | None:
        r"""
        The hardware module this interface belongs to, if any.
        """
    @property
    def poe(self) -> bool | None:
        r"""
        Whether power over Ethernet is enabled, when the platform reports it.
        """
    @property
    def speed(self) -> tuple[int, ...] | None:
        r"""
        The configured speeds, if any are pinned.
        """
    @property
    def platform(self) -> hier_config.models.Platform:
        r"""
        The platform this interface view interprets the config as.
        """
    @property
    def capabilities(self) -> frozenset[str]:
        r"""
        The optional capabilities this platform's interface view supports.

        Mirrors the mixins the pure-Python views used to inherit, so
        `isinstance(view, InterfaceVlanViewMixin)` still answers correctly.
        """

class HConfigBase:
    r"""
    Abstract base class for the hierarchical configuration tree.

    Both `HConfig` (the root) and `HConfigChild` (individual nodes) inherit from
    this class.  It provides the shared tree-manipulation API: adding, searching,
    and diffing children, as well as the `_future` / `_config_to_get_to` algorithms
    that power `WorkflowRemediation`.
    """
    @property
    def depth(self) -> int:
        r"""
        Distance from the root of the configuration tree.
        """
    @property
    def is_leaf(self) -> bool:
        r"""
        True if there are no children and is not an instance of `HConfig`.
        """
    @property
    def is_branch(self) -> bool:
        r"""
        True if there are children or is an instance of `HConfig`.
        """
    @property
    def tags(self) -> frozenset[str]:
        r"""
        Recursive access to tags on all leaf nodes.
        """
    @tags.setter
    def tags(self, value: collections.abc.Iterable[str]) -> None: ...
    @property
    def children(self) -> HConfigChildren:
        r"""
        The direct children of this node.
        """
    def __new__(cls) -> typing_extensions.Self: ...
    def path(self) -> collections.abc.Iterator[str]: ...
    def tags_add(self, tag: str | collections.abc.Iterable[str]) -> None:
        r"""
        Add a tag to self._tags on all leaf nodes.
        """
    def tags_remove(self, tag: str | collections.abc.Iterable[str]) -> None:
        r"""
        Remove a tag from self._tags on all leaf nodes.
        """
    def add_tags(self, tag: str | collections.abc.Iterable[str]) -> None:
        r"""
        v4 name for `tags_add()`.
        """
    def remove_tags(self, tag: str | collections.abc.Iterable[str]) -> None:
        r"""
        v4 name for `tags_remove()`.
        """
    def indented_text(
        self, style: hier_config.models.TextStyle | None = None, tag: str | None = None
    ) -> str:
        r"""
        v4 name for `cisco_style_text()`.
        """
    def cisco_style_text(
        self, style: hier_config.models.TextStyle | None = None, tag: str | None = None
    ) -> str:
        r"""
        Return a Cisco style formated line i.e. `indentation_level` + text ! comments.
        """
    def add_child(
        self,
        text: str,
        *,
        return_if_present: bool = False,
        check_if_present: bool = True,
    ) -> HConfigChild:
        r"""
        Add a child instance of `HConfigChild`.
        """
    def add_children(self, lines: collections.abc.Iterable[str]) -> None:
        r"""
        Add child instances of `HConfigChild`.
        """
    def add_deep_copy_of(
        self, child_to_add: HConfigChild, *, merged: bool = False
    ) -> HConfigChild:
        r"""
        Add a nested copy of a child to self.
        """
    def add_shallow_copy_of(
        self, child_to_add: HConfigChild, *, merged: bool = False
    ) -> HConfigChild:
        r"""
        Add a nested copy of a `child_to_add` to self.children.
        """
    def del_child(self, child: HConfigChild) -> None: ...
    def del_child_by_text(self, text: str) -> None: ...
    def move_child(self, child: HConfigChild) -> None: ...
    def get_children_object(self) -> HConfigChildren: ...
    def all_children(self) -> collections.abc.Iterator[HConfigChild]:
        r"""
        Recursively find and yield all children at each hierarchy.
        """
    def all_children_sorted(self) -> collections.abc.Sequence[HConfigChild]:
        r"""
        Recursively find and yield all children sorted at each hierarchy.
        """
    def all_children_sorted_by_tags(
        self,
        include_tags: collections.abc.Iterable[str] | None = None,
        exclude_tags: collections.abc.Iterable[str] | None = None,
    ) -> collections.abc.Sequence[HConfigChild]:
        r"""
        Yield all children recursively that match include/exclude tags.
        """
    def _with_tags(
        self, tags: collections.abc.Iterable[str], new_instance: HConfig | HConfigChild
    ) -> HConfig | HConfigChild: ...
    def get_child(
        self,
        *,
        equals: str | (frozenset[str] | set[str]) | None = None,
        startswith: str | tuple[str, ...] | None = None,
        endswith: str | tuple[str, ...] | None = None,
        contains: str | tuple[str, ...] | None = None,
        re_search: str | None = None,
    ) -> HConfigChild | None:
        r"""
        Find a child by `text_match` rule. If it is not found, return None.
        """
    def get_children(
        self,
        *,
        equals: str | (frozenset[str] | set[str]) | None = None,
        startswith: str | tuple[str, ...] | None = None,
        endswith: str | tuple[str, ...] | None = None,
        contains: str | tuple[str, ...] | None = None,
        re_search: str | None = None,
    ) -> collections.abc.Iterator[HConfigChild]:
        r"""
        Find all children matching a `text_match` rule and return them.
        """
    def get_child_deep(
        self, match_rules: tuple[hier_config.models.MatchRule, ...]
    ) -> HConfigChild | None:
        r"""
        Find the first child recursively given a tuple of `MatchRules`.
        """
    def get_children_deep(
        self, match_rules: tuple[hier_config.models.MatchRule, ...]
    ) -> collections.abc.Iterator[HConfigChild]:
        r"""
        Find children recursively given a tuple of `MatchRules`.
        """
    def lineage(self) -> collections.abc.Iterator[HConfigChild]: ...
    def lines(
        self, *, sectional_exiting: bool = False
    ) -> collections.abc.Iterable[str]: ...
    def dump_simple(self, *, sectional_exiting: bool = False) -> tuple[str, ...]: ...
    def to_lines(self, *, sectional_exiting: bool = False) -> tuple[str, ...]:
        r"""
        v4 name for `dump_simple()`.
        """
    def unified_diff(
        self, target: HConfig | HConfigChild
    ) -> collections.abc.Iterator[str]:
        r"""
        Yield unified-diff lines comparing self to target.

        Each yielded string is prefixed with ``-`` (present in self but not
        target) or ``+`` (present in target but not self), followed by the
        appropriate indentation and the command text.

        .. `note::`
            This algorithm does not account for duplicate child differences
            (e.g. two ``endif`` tokens in an IOS-XR route-policy) and does
            not preserve command order where it matters (e.g. ACLs without
            sequence numbers).  Use sequence numbers in ACL entries when
            order is significant.

        Produces output similar to :func:`difflib.unified_diff`.
        """
    def use_sectional_overwrite(self) -> bool:
        r"""
        Determines if self.text matches a sectional overwrite rule.
        """
    def use_sectional_overwrite_without_negation(self) -> bool:
        r"""
        Check self's text to see if negation should be handled by
        overwriting the section without first negating it.
        """
    def delete_sectional_exit(self) -> None: ...
    def __len__(self) -> int:
        r"""
        Return len(self).
        """
    def __bool__(self) -> bool:
        r"""
        True if self else False
        """
    def __contains__(self, text: str, /) -> bool:
        r"""
        Return key in self.
        """
    def __iter__(self) -> collections.abc.Iterator[HConfigChild]:
        r"""
        Implement iter(self).
        """

@typing.final
class HConfigChildren:
    r"""
    Ordered collection of `HConfigChild` objects with fast text-keyed look-up.

    The native arena preserves sibling order and indexes children by text.
    When duplicate child text is allowed by the driver, text-keyed retrieval
    returns the first occurrence while iteration preserves all entries.
    """
    @typing.overload
    def __getitem__(self, item: int | str, /) -> HConfigChild:
        r"""
        Return the child at an index or text key.
        """
    @typing.overload
    def __getitem__(self, item: slice, /) -> list[HConfigChild]:
        r"""
        Return children selected by a slice, preserving order.
        """
    @typing.overload
    def get(self, key: str, default: None = None) -> HConfigChild | None:
        r"""
        Look up a child by text, returning None when absent.
        """
    @typing.overload
    def get(
        self, key: str, default: hier_config._typing.DefaultT
    ) -> HConfigChild | hier_config._typing.DefaultT:
        r"""
        Look up a child by text, preserving the type of the supplied default.
        """
    def __len__(self) -> int:
        r"""
        Return len(self).
        """
    def __contains__(self, text: str, /) -> bool:
        r"""
        Return key in self.
        """
    def __setitem__(self, item: int, value: HConfigChild, /) -> None:
        r"""
        Set self[key] to value.
        """
    def index(self, child: HConfigChild) -> int: ...
    def append(self, child: HConfigChild) -> HConfigChild: ...
    def clear(self) -> None:
        r"""
        Delete all children.
        """
    def delete(self, child_or_text: HConfigChild | str) -> None:
        r"""
        Delete a child from self._data and self._mapping.
        """
    def extend(self, children: collections.abc.Iterable[HConfigChild]) -> None:
        r"""
        Add child instances of `HConfigChild`.
        """
    def rebuild_mapping(self) -> None:
        r"""
        Rebuild self._mapping.
        """
    def __iter__(self) -> collections.abc.Iterator[HConfigChild]:
        r"""
        Implement iter(self).
        """
    def __eq__(self, other: object, /) -> bool:
        r"""
        Return self==value.
        """
    def __ne__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int:
        r"""
        Return hash(self).
        """

@typing.final
class HConfigChildrenIter:
    r"""
    Iterate native child handles in sibling order.
    """
    def __iter__(self) -> HConfigChildrenIter: ...
    def __next__(self) -> HConfigChild: ...

class HConfigView:
    r"""
    A structured, read-only view over a whole configuration.

    Instances are constructed with an `HConfig`, exactly as the previous
    pure-Python `HConfigViewBase` subclasses were, so `driver.view_class`
    keeps working for custom drivers.
    """
    @property
    def config(self) -> HConfig:
        r"""
        The `HConfig` this view reads from.
        """
    @property
    def platform(self) -> hier_config.models.Platform:
        r"""
        The platform this view interprets the config as.
        """
    @property
    def hostname(self) -> str | None:
        r"""
        The configured hostname, if the platform records one.
        """
    @property
    def ipv4_default_gw(self) -> ipaddress.IPv4Address | None:
        r"""
        The IPv4 default gateway, if one is configured.
        """
    @property
    def interface_views(self) -> list[ConfigViewInterface]:
        r"""
        A view for every interface in the configuration.
        """
    @property
    def bundle_interface_views(self) -> list[ConfigViewInterface]:
        r"""
        A view for every interface that is a link bundle.
        """
    @property
    def interfaces(self) -> list[HConfigChild]:
        r"""
        The `HConfigChild` holding each interface's config block.
        """
    @property
    def interfaces_names(self) -> list[str]:
        r"""
        The name of every configured interface.
        """
    @property
    def interface_names_mentioned(self) -> frozenset[str]:
        r"""
        Every interface name mentioned anywhere in the configuration.
        """
    @property
    def location(self) -> str:
        r"""
        The SNMP location string, or an empty string when unset.
        """
    @property
    def module_numbers(self) -> list[int]:
        r"""
        Every hardware module number referenced by an interface.
        """
    @property
    def stack_members(self) -> list[hier_config.platforms.models.StackMember]:
        r"""
        The members of a switch stack, if the platform reports one.
        """
    @property
    def vlan_ids(self) -> frozenset[int]:
        r"""
        Every VLAN ID defined in the configuration.
        """
    @property
    def vlans(self) -> list[hier_config.platforms.models.Vlan]:
        r"""
        Every VLAN defined in the configuration.
        """
    def __new__(cls, config: HConfig) -> typing_extensions.Self:
        r"""
        Build a view over `config`.
        """
    def interface_view_by_name(self, name: str) -> ConfigViewInterface | None:
        r"""
        The view for `name`, or `None` when no such interface exists.
        """
    @staticmethod
    def dot1q_mode_from_vlans(
        untagged_vlan: int | None = None,
        tagged_vlans: tuple[int, ...] | None = None,
        *,
        tagged_all: bool = False,
    ) -> hier_config.platforms.models.InterfaceDot1qMode | None:
        r"""
        Classify a switchport from its native and tagged VLANs.
        """

class HierConfigError(builtins.Exception):
    r"""
    Base exception for hierarchical configuration errors.
    """

class WorkflowRemediation:
    r"""
    Native implementation of remediation and rollback workflow.
    Manages configuration workflows for a network device by comparing
    running and generated configurations and creating remediations to align
    the device with the intended configuration state.

    Attributes:
        `running_config` (HConfig): The current configuration of the network device.
        `generated_config` (HConfig): The target configuration for the network device.

    Raises:
        `ValueError`: If `running_config` and `generated_config` have different drivers.

    Example:
        Initialize `WorkflowRemediation` with the running and generated configurations
        and generate remediation and rollback configurations.

    ```python
    from hier_config import WorkflowRemediation, get_hconfig
    from hier_config.models import Platform

    # Create running and generated configurations as HConfig objects
    running_config = get_hconfig(Platform.CISCO_IOS, "running_config_text")
    generated_config = get_hconfig(Platform.CISCO_IOS, "generated_config_text")

    # Initialize WorkflowRemediation with running and generated configurations
    workflow = WorkflowRemediation(running_config, generated_config)

    # Generate the remediation configuration to apply the target configuration to the device
    remediation_config = workflow.remediation_config
    print("Remediation configuration:")
    for line in remediation_config.all_children_sorted():
        print(line.cisco_style_text())

    # Generate the rollback configuration to revert back to the running configuration
    rollback_config = workflow.rollback_config
    print("Rollback configuration:")
    for line in rollback_config.all_children_sorted():
        print(line.cisco_style_text())
    ```
    """
    @property
    def plugins(self) -> tuple[collections.abc.Callable[[HConfig], None], ...]:
        r"""
        The remediation plugins applied to every generated remediation.
        """
    @property
    def running_config(self) -> HConfig: ...
    @property
    def generated_config(self) -> HConfig: ...
    @property
    def remediation_config(self) -> HConfig: ...
    @property
    def rollback_config(self) -> HConfig: ...
    def __new__(
        cls,
        running_config: HConfig,
        generated_config: HConfig,
        plugins: collections.abc.Iterable[collections.abc.Callable[[HConfig], None]]
        | None = None,
    ) -> typing_extensions.Self: ...
    def __init__(
        self,
        running_config: HConfig,
        generated_config: HConfig,
        plugins: collections.abc.Iterable[collections.abc.Callable[[HConfig], None]]
        | None = None,
    ) -> None: ...
    @classmethod
    def from_strings(
        cls,
        platform: hier_config.models.Platform | str,
        running_text: str,
        generated_text: str,
    ) -> WorkflowRemediation:
        r"""
        Creates a workflow by parsing running and generated configuration strings
        using the default driver for `platform` in Rust with the GIL released.
        """
    def remediation_netconf_xml(
        self, *, list_keys: tuple[str, ...] | None = None
    ) -> str:
        r"""
        Renders the remediation as a NETCONF edit-config payload.

        Requires running and generated configs built by `HConfig.from_xml()`.
        """
    def remediation_json(
        self, *, list_keys: tuple[str, ...] | None = None
    ) -> hier_config.formats.GnmiRemediation:
        r"""
        Renders the remediation as a gNMI-SetRequest-style dict.

        Requires running and generated configs built by `HConfig.from_json()`.
        """
    def apply_remediation_tag_rules(
        self, tag_rules: tuple[hier_config.models.TagRule, ...]
    ) -> None:
        r"""
        Applies tag rules to selectively label parts of the remediation configuration.

        Args:
            tag_rules: A set of tag rules specifying sections to tag.

        Notes:
            This method is useful for managing configuration changes by marking specific
            parts of the config for conditional remediation.
        """
    def remediation_text(
        self,
        include_tags: collections.abc.Iterable[str] | None = None,
        exclude_tags: collections.abc.Iterable[str] | None = None,
    ) -> str:
        r"""
        Remediation configuration as text, filtered by included and excluded tags.
        """
    def remediation_config_filtered_text(
        self,
        include_tags: collections.abc.Iterable[str] | None = None,
        exclude_tags: collections.abc.Iterable[str] | None = None,
    ) -> str:
        r"""
        Returns the remediation configuration as text, filtered by included and excluded tags.

        Args:
            include_tags: Tags to include in the output.
            exclude_tags: Tags to exclude from the output.

        Returns:
            str: The filtered remediation configuration in a text format.

        Notes:
            - If no tags are provided, the complete sorted remediation configuration is returned.
            - Sorting respects configuration hierarchy and specified tags.
        """
    def rollback_text(
        self,
        include_tags: collections.abc.Iterable[str] | None = None,
        exclude_tags: collections.abc.Iterable[str] | None = None,
    ) -> str:
        r"""
        Rollback configuration as text, filtered by included and excluded tags.
        """
    def rollback_config_filtered_text(
        self,
        include_tags: collections.abc.Iterable[str] | None = None,
        exclude_tags: collections.abc.Iterable[str] | None = None,
    ) -> str:
        r"""
        Rollback configuration as text, filtered by included and excluded tags.
        """

class DuplicateChildError(HierConfigError):
    r"""
    A child with this text already exists in the destination.
    """

class HConfig(HConfigBase):
    r"""
    A class for representing and comparing Cisco like configurations in a
    hierarchical tree data structure.
    """
    @property
    def driver(self) -> hier_config.platforms.driver_base.HConfigDriverBase: ...
    @property
    def root(self) -> HConfig:
        r"""
        The `HConfig` object at the base of the tree.
        """
    @property
    def parent(self) -> HConfig: ...
    @property
    def real_indent_level(self) -> int: ...
    @property
    def is_leaf(self) -> builtins.bool: ...
    @property
    def is_branch(self) -> builtins.bool: ...
    def __new__(
        cls, driver: hier_config.platforms.driver_base.HConfigDriverBase
    ) -> typing_extensions.Self: ...
    def __init__(
        self, driver: hier_config.platforms.driver_base.HConfigDriverBase
    ) -> None: ...
    def instantiate_child(self, text: str) -> HConfigChild: ...
    def merge(self, other: HConfig | collections.abc.Iterable[HConfig]) -> HConfig:
        r"""
        Merges other `HConfig` objects into this one.
        """
    def _load_native(self, config_raw: str, run_post_load: bool = True) -> None:
        r"""
        Parses a raw configuration string entirely in Rust.

        Runs `full_text_sub`, the platform preprocessor, the line-by-line parse and
        sectional-exit removal in a single FFI call with the GIL released, allocating
        no Python objects. When `run_post_load` is true the natively-implemented
        post-load callbacks for the platform are applied as well; callers pass false
        when a custom driver supplies its own Python callbacks.
        """
    def _load_fast_native(
        self, lines: str | collections.abc.Iterable[str], run_post_load: bool
    ) -> None:
        r"""
        Parses pre-formatted `lines` into this tree inside a single FFI call.

        Mirrors [`Self::_load_native`] but applies only `per_line_sub` rules, matching
        the semantics of `get_hconfig_fast_load`.

        `lines` may be a single `str` — which is split on line boundaries in Rust,
        avoiding any per-line marshalling — or any iterable of `str`.

        # Errors

        Returns an error if `lines` is not a `str` or an iterable of `str`, or if a
        line cannot be inserted into the tree.
        """
    def _load_file_native(self, path: str, run_post_load: bool = True) -> None:
        r"""
        Reads and parses an on-disk config file into this tree inside a single FFI call.

        Reads the file directly via `std::fs::read_to_string` with the GIL released,
        avoiding intermediate Python `str` allocations.
        """
    def _load_from_dump_native(
        self, dump: collections.abc.Iterable[hier_config.models.DumpLine]
    ) -> None:
        r"""
        Reconstructs the tree structure from a [`Dump`] model inside a single FFI call.

        Unpacks line attributes and delegates tree reconstruction to native Rust in O(N)
        without per-node Python FFI round-trips.
        """
    def add_children_deep(self, lines: collections.abc.Iterable[str]) -> HConfigChild:
        r"""
        Add child instances of `HConfigChild` deeply.
        """
    def add_ancestor_copy_of(
        self, parent_to_add: HConfigChild
    ) -> HConfig | HConfigChild:
        r"""
        Add a copy of the ancestry of `parent_to_add` to self
        and return the deepest child which is equivalent to `parent_to_add`.
        """
    def difference(self, target: HConfig) -> HConfig:
        r"""
        Creates a new `HConfig` object with the config from self that is not in target.
        """
    def remediation(self, target: HConfig, delta: HConfig | None = None) -> HConfig:
        r"""
        v4 name for `config_to_get_to()`.
        """
    def config_to_get_to(
        self, target: HConfig, delta: HConfig | None = None
    ) -> HConfig:
        r"""
        Figures out what commands need to be executed to transition from self to target.
        self is the source data structure(i.e. the `running_config`),
        target is the destination(i.e. `generated_config`).
        """
    def future(self, config: HConfig, *, prune_empty_branches: bool = False) -> HConfig:
        r"""
        EXPERIMENTAL - predict the future config after config is applied to self.

        The quality of this method's output will in part depend on how well
        the OS options are tuned. Ensuring that idempotency rules are accurate is
        especially important.

        With `prune_empty_branches`, sections that the change emptied out are
        removed, matching devices that prune empty stanzas on commit; sections
        that were already empty are kept.
        """
    def future_with_report(
        self, config: HConfig, *, prune_empty_branches: bool = False
    ) -> tuple[HConfig, hier_config.tree_algorithms.FutureReport]:
        r"""
        Like `future()`, but also reports how the change's negations resolved.

        Returns `(future_config, FutureReport)`. The report's nodes belong to
        the returned tree, so callers can walk their surrounding context.
        """
    def deep_copy(self) -> HConfig:
        r"""
        Return a copy of this object.
        """
    def with_tags(self, tags: collections.abc.Iterable[str]) -> HConfig:
        r"""
        Returns a new instance recursively containing children that only have a subset of tags.
        """
    def _is_object_referenced(
        self,
        name: builtins.str,
        reference_locations: collections.abc.Iterable[
            hier_config.models.ReferenceLocation
        ],
    ) -> builtins.bool: ...
    def unused_objects(self) -> collections.abc.Sequence[HConfigChild]:
        r"""
        Yield top-level children that are defined objects with no references.

        Uses ``self.driver.rules.unused_objects`` to identify object definitions,
        extract their names, and search for references across the config tree.
        Objects with zero references are yielded.
        """
    def set_order_weight(self) -> HConfig:
        r"""
        Sets self.order integer on all children.
        """
    def dump_simple(
        self, *, sectional_exiting: builtins.bool = False
    ) -> tuple[str, ...]: ...
    @classmethod
    def from_text(
        cls,
        platform_or_driver: hier_config.models.Platform
        | str
        | hier_config.platforms.driver_base.HConfigDriverBase,
        config_text: str | os.PathLike[str] | None = None,
    ) -> HConfig:
        r"""
        Create an `HConfig` from raw configuration text (or a Path to it).
        """
    @classmethod
    def from_lines(
        cls,
        platform_or_driver: hier_config.models.Platform
        | str
        | hier_config.platforms.driver_base.HConfigDriverBase,
        lines: collections.abc.Iterable[str],
    ) -> HConfig:
        r"""
        Create an `HConfig` from pre-split configuration lines (fast load).
        """
    @classmethod
    def from_dump(
        cls,
        platform_or_driver: hier_config.models.Platform
        | str
        | hier_config.platforms.driver_base.HConfigDriverBase,
        dump: hier_config.models.Dump,
    ) -> HConfig:
        r"""
        Reconstruct an `HConfig` from a serialized `Dump`.
        """
    @classmethod
    def from_json(
        cls,
        platform_or_driver: hier_config.models.Platform
        | str
        | hier_config.platforms.driver_base.HConfigDriverBase,
        data: str | dict[str, hier_config._typing.ValueT],
        *,
        list_keys: tuple[str, ...] | None = None,
    ) -> HConfig:
        r"""
        Create an `HConfig` from a JSON object or JSON text.
        """
    @classmethod
    def from_xml(
        cls,
        platform_or_driver: hier_config.models.Platform
        | str
        | hier_config.platforms.driver_base.HConfigDriverBase,
        source: str,
        *,
        list_keys: tuple[str, ...] | None = None,
    ) -> HConfig:
        r"""
        Create an `HConfig` from an XML document.
        """
    def to_json(self, *, indent: builtins.int | None = 2) -> str:
        r"""
        Render a tree built by `from_json` back to JSON text.
        """
    def to_xml(self) -> str:
        r"""
        Render a tree built by `from_xml` back to XML text.
        """
    def to_lines(self, *, sectional_exiting: builtins.bool = False) -> tuple[str, ...]:
        r"""
        v4 name for `dump_simple()`.
        """
    def dump(self) -> hier_config.models.Dump:
        r"""
        Dump loaded `HConfig` data.
        """
    def __deepcopy__(self, memo: dict[int, object]) -> HConfig: ...
    def __reduce__(
        self,
    ) -> tuple[
        collections.abc.Callable[..., HConfig],
        tuple[
            hier_config.platforms.driver_base.HConfigDriverBase, hier_config.models.Dump
        ],
    ]: ...
    def __eq__(self, other: object, /) -> bool:
        r"""
        Return self==value.
        """
    def __ne__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int:
        r"""
        Return hash(self).
        """

class HConfigChild(HConfigBase):
    r"""
    A single node in the hierarchical configuration tree.

    Each `HConfigChild` holds one configuration line (`text`), an ordered
    collection of its own children, optional tags/comments, and a reference
    back to its parent.  The tree is rooted at an `HConfig` instance; every
    other node is an `HConfigChild`.
    """
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def indentation(self) -> str: ...
    @property
    def parent(self) -> HConfig | HConfigChild: ...
    @parent.setter
    def parent(self, value: HConfig | HConfigChild) -> None: ...
    @property
    def root(self) -> HConfig:
        r"""
        The `HConfig` object at the base of the tree.
        """
    @property
    def driver(self) -> hier_config.platforms.driver_base.HConfigDriverBase: ...
    @property
    def text_without_negation(self) -> str: ...
    @property
    def sectional_exit(self) -> str | None: ...
    @property
    def sectional_exit_text_parent_level(self) -> bool: ...
    @property
    def real_indent_level(self) -> int: ...
    @real_indent_level.setter
    def real_indent_level(self, value: int) -> None: ...
    @property
    def order_weight(self) -> int: ...
    @order_weight.setter
    def order_weight(self, value: int) -> None: ...
    @property
    def new_in_config(self) -> bool: ...
    @new_in_config.setter
    def new_in_config(self, value: bool) -> None: ...
    @property
    def comments(self) -> set[str]: ...
    @comments.setter
    def comments(self, value: collections.abc.Iterable[str]) -> None: ...
    @property
    def instances(self) -> list[hier_config.models.Instance]: ...
    @instances.setter
    def instances(
        self, value: collections.abc.Iterable[hier_config.models.Instance]
    ) -> None: ...
    @property
    def facts(self) -> dict[str, object]: ...
    @facts.setter
    def facts(self, value: dict[str, object]) -> None: ...
    @property
    def instance(self) -> hier_config.models.Instance: ...
    def __new__(
        cls, parent: HConfig | HConfigChild, text: str
    ) -> typing_extensions.Self: ...
    def _default(self) -> HConfigChild:
        r"""
        Prefix the line with `default ` in place and return this child.
        """
    def use_default_for_negation(self, config: HConfigChild) -> bool: ...
    def line_inclusion_test(
        self,
        include_tags: collections.abc.Iterable[str],
        exclude_tags: collections.abc.Iterable[str],
    ) -> bool:
        r"""
        Given the `line_tags`, `include_tags`, and `exclude_tags`,
        determine if the line should be included.
        """
    def add_children_deep(self, lines: collections.abc.Iterable[str]) -> HConfigChild:
        r"""
        Add child instances of `HConfigChild` deeply.
        """
    def delete(self) -> None:
        r"""
        Delete the current object from its parent.
        """
    def move(self, new_parent: HConfig | HConfigChild) -> None:
        r"""
        Move this node under another root or child, preserving its descendants.
        """
    def negate(self) -> HConfigChild:
        r"""
        Negate self.text using driver-specific negation rules.

        Negation is resolved in the following priority order:

        1. ``negate_with`` rule — replaces ``self.text`` with a custom
           negation string defined in the driver (e.g. ``no ip route``).
        2. ``negation_default_when`` rule — rewrites the command to its
           ``default`` form (e.g. ``no shutdown`` → ``default shutdown``).
        3. ``negation_sub`` rule — applies a regex substitution to the
           negated text (e.g. truncating after a specific token).
        4. ``swap_negation`` — toggles the negation prefix/declaration
           prefix (e.g. ``shutdown`` ↔ ``no shutdown``).

        Returns self so that callers can chain further operations.
        """
    def is_match(
        self,
        *,
        equals: str | (frozenset[str] | set[str]) | None = None,
        startswith: str | tuple[str, ...] | None = None,
        endswith: str | tuple[str, ...] | None = None,
        contains: str | tuple[str, ...] | None = None,
        re_search: str | None = None,
    ) -> bool:
        r"""
        Return True if ``self.text`` satisfies all supplied criteria.

        All arguments are optional.  When *all* arguments are ``None`` the
        method returns ``True`` (matches everything).  When multiple arguments
        are provided, **all** must match.

        Args:
            equals: Exact string match, or a frozenset of acceptable values.
            startswith: ``str.startswith`` prefix (str or tuple of strs).
            endswith: ``str.endswith`` suffix (str or tuple of strs).
            contains: Substring(s) that must appear in ``self.text``.
            re_search: Regular expression applied via :func:`re.search`.

        Returns:
            ``True`` if every non-``None`` criterion is satisfied.
        """
    def is_lineage_match(self, rules: tuple[hier_config.models.MatchRule, ...]) -> bool:
        r"""
        A generic test against a lineage of `HConfigChild` objects.
        """
    def is_idempotent_command(
        self, other_children: collections.abc.Iterable[HConfigChild]
    ) -> bool:
        r"""
        Determine if self.text is an idempotent change.
        """
    def overwrite_with(
        self,
        target: HConfigChild,
        delta: HConfig | HConfigChild,
        *,
        negate: bool = True,
    ) -> None:
        r"""
        Overwrite self's section in delta with a deep copy of target.

        When the children of self and target differ, this method mutates
        ``delta`` in-place: the existing entry for ``self.text`` is negated
        (if ``negate=True``) or simply deleted (if ``negate=False``), and a
        fresh deep copy of ``target`` is appended.  A ``"re-create section"``
        comment is attached to the new entry, and a ``"dropping section"``
        comment is added to the negated entry when applicable.

        Used by :meth:`_config_to_get_to_right` when a sectional-overwrite
        rule is active for ``self.text``.
        """
    def __deepcopy__(self, memo: dict[int, object]) -> HConfigChild: ...
    def __lt__(self, other: HConfigChild, /) -> bool:
        r"""
        Return self<value.
        """
    def __eq__(self, other: object, /) -> bool:
        r"""
        Return self==value.
        """
    def __ne__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int:
        r"""
        Return hash(self).
        """

class InvalidConfigError(HierConfigError):
    r"""
    The supplied configuration is malformed.
    """

def config_preprocessor(platform_str: str, config_text: str) -> str:
    r"""
    Applies platform-specific configuration preprocessor (e.g. converting to set commands for JunOS/VyOS/SRL).
    """

def convert_to_set_commands(config_raw: str) -> str:
    r"""
    Converts a hierarchical configuration into flat set commands.
    """

def driver_swap_negation(platform_str: str, text: str) -> str:
    r"""
    Swaps the negation prefix of a command string for a platform according to its driver syntax rules.
    """

def formats_from_json(
    driver_obj: object, data: str, list_keys: list[str] | None = None
) -> HConfig:
    r"""
    Builds an `HConfig` from JSON text.
    """

def formats_from_xml(
    driver_obj: object, source: str, list_keys: list[str] | None = None
) -> HConfig:
    r"""
    Builds an `HConfig` from an XML document.
    """

def formats_to_gnmi_json(
    remediation: HConfig,
    running: HConfig | None = None,
    list_keys: list[str] | None = None,
) -> hier_config.formats.GnmiRemediation:
    r"""
    Renders a remediation as a gNMI-`SetRequest`-style dict.
    """

def formats_to_json(config: HConfig, indent: builtins.int | None = 2) -> str:
    r"""
    Renders an `HConfig` built by `formats_from_json` back to JSON text.
    """

def formats_to_netconf_xml(
    remediation: HConfig,
    running: HConfig | None = None,
    list_keys: list[str] | None = None,
) -> str:
    r"""
    Renders a remediation as a NETCONF `edit-config` payload.
    """

def formats_to_xml(config: HConfig) -> str:
    r"""
    Renders an `HConfig` built by `formats_from_xml` back to XML text.
    """

def get_platform_rules_json(platform_str: str) -> str:
    r"""
    Returns the canonical platform rules JSON for a given platform name or ID.
    """
