"""Type stubs for the exception hierarchy.

``HierConfigError`` and ``DuplicateChildError`` come from the compiled
extension, so they need declaring here for the same reason the tree shims do.
"""

class HierConfigError(Exception): ...
class DuplicateChildError(HierConfigError): ...
class DriverNotFoundError(HierConfigError): ...
class InvalidConfigError(HierConfigError): ...
class IncompatibleDriverError(HierConfigError): ...

__all__: tuple[str, ...]
